version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "2700:2700"
    environment:
      - VOSK_SERVER_INTERFACE=0.0.0.0
      - VOSK_SERVER_PORT=2700
      - VOSK_MODEL_PATH=/app/model
      - VOSK_CERT_FILE=/app/certs/cert.pem
      - VOSK_KEY_FILE=/app/certs/key.pem
      - VOSK_DUMP_FILE=/app/logs/dump.log
    volumes:
      - ./model:/app/model
      - ./certs:/app/certs
      - ./logs:/app/logs

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  default:
    external:
      name: my-network
